# Generated by Django 4.2.6 on 2024-05-14 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supermercado1Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Supermercado2Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('encrypted_password', models.CharField(max_length=120)),
                ('birthdate', models.DateField()),
                ('token', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FavSupermercado2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lahuertadeabril02app.supermercado2producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lahuertadeabril02app.user')),
            ],
        ),
        migrations.CreateModel(
            name='FavSupermercado1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lahuertadeabril02app.supermercado1producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lahuertadeabril02app.user')),
            ],
        ),
    ]
