# Generated by Django 4.2.6 on 2024-05-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lahuertadeabril02app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermercado1producto',
            name='origen',
            field=models.CharField(default='Galicia', max_length=200),
        ),
        migrations.AddField(
            model_name='supermercado2producto',
            name='origen',
            field=models.CharField(default='Galicia', max_length=200),
        ),
    ]
